# Generated by Django 5.2.7 on 2025-11-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_payment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True,
                help_text="Введите город проживания",
                max_length=100,
                null=True,
                verbose_name="Город",
            ),
        ),
    ]
