# Generated by Django 5.2.7 on 2025-11-13 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="owner",
        ),
    ]
