# Generated by Django 5.2.7 on 2025-11-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_status",
            field=models.CharField(default="unpaid", verbose_name="Статус платежа"),
        ),
    ]
