# Generated by Django 5.2.7 on 2025-11-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_payment_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="link",
            field=models.URLField(
                default=None,
                null=True,
                blank=True,
                max_length=400,
                verbose_name="Ссылка для оплаты",
            ),
        ),
    ]
