# Generated by Django 5.2.7 on 2025-11-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_payment_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True,
                default=None,
                max_length=400,
                null=True,
                verbose_name="Ссылка для оплаты",
            ),
        ),
    ]
