# Generated by Django 5.2.7 on 2025-11-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_payment_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="link",
            field=models.URLField(
                default="отсутствует", max_length=400, verbose_name="Ссылка для оплаты"
            ),
        ),
    ]
