# Generated by Django 5.2.7 on 2025-11-07 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="course",
            field=models.ForeignKey(
                blank=True,
                max_length=150,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="study.course",
                verbose_name="Курсы",
            ),
        ),
    ]
