# Generated by Django 5.2.7 on 2025-11-20 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0004_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["course", "name"],
                "verbose_name": "урок",
                "verbose_name_plural": "уроки",
            },
        ),
    ]
