# Generated by Django 5.2.7 on 2025-11-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0005_alter_lesson_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
