# Generated by Django 5.2.7 on 2025-11-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0006_course_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
